# Site settings
title: bernikr.github.io
description: A small blog with random stuff I do
permalink: /:title
github_username: bernikr

# Build settings
markdown: kramdown
future: true

sass:
    style: compressed

gems:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-coffeescript

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: post
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: page
