# Site settings
title: bernikr.github.io
url: https://bernikr.github.io
description: A small blog with random stuff I do
permalink: /b/:title
social:
  github: bernikr

# Build settings
markdown: kramdown
future: true

sass:
  style: compressed

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-coffeescript

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
  # This fixes an Invalid-Date-bug when using drafts
  - scope:
      path: "_drafts"
    values:
      sitemap: false
